const Map<String, String> ar = {
  'sign in': 'تسجيل الدخول',
  'sign up': 'تسجيل حساب جديد',
  'localization': 'تغيير اللغة',
  'Sign in': 'تسجيل الدخول',
  'Log In': 'دخول',
  'Enter your email': 'ادخل البريد الالكتروني',
  'Not valid email form': 'بريد الكتروني غير صحيح',
  'Type your message here...': 'أكتب رسالتك هنا...',
  'Sign Up': 'تسجيل حساب جديد',
  'Enter your password': 'ادخل كلمة المرور',
  'password must be at least 8 digits': 'يجب ألا تقل كلمة المرور عن 8 خانات',
  'email expression is not valid': 'صيغة البريد الإلكتروني غير صحيحه',
  'An error': 'خطأ',
  'email or password are wrong': 'البريد الإلكتروني او كلمة المرور غير صحيحه',
  'Okay': 'موافق',
  'Blood Bank': 'بنك الدم',
  'Developed By Hero Soft Company': 'تم تطويره من خلال شركة Hero Soft ',
  'Chats': 'المحادثات',
  'Search': 'بحث',
  'No Chats!': 'لا توجد محادثات',
  'Post has been deleted': 'تم حذف المنشور',
  'no more details': 'لا يوجد تفاصيل اخري',
  'No posts shared!': 'لم يتم مشاركة اي منشورات بعد',
  'Search for user': 'بحث عن مستخدم',
  'blood type:': 'فصيلة الدم',
  'Governorate: ': 'المحافظة  ',
  'No users with this blood type': 'لا يوجد مستخدمون بفصيلة الدم هذه',
  'click search to filter': 'انقر فوق بحث للتصفية',
  'can\'t be less than 3 digits': 'لا يمكن أن يكون أقل من 3 حروف',
  'Enter password': 'أدخل كلمة المرور',
  'Confirm password': 'تأكد كلمة المرور',
  'Not the same as password': 'الكلمات غير متطابقتان',
  'Enter Your Phone Number': 'أدخل رقم هاتفك',
  'can\'t be less than 11 number': 'لا يمكن أن يكون أقل من 11 خانة',
  'must be 18 or older': 'يجب أن يكون عمرك 18 عامًا أو أكبر',
  'blood type': 'فصيلة دمك',
  'This email is already exist': 'هذا البريد الإلكتروني موجود بالفعل',
  'Blood Bank  ': 'بنك الدم  ',
  // 'Alexandera': 'الإسكندرية',
  // 'Cairo': 'القاهرة',
  // 'Beheira': 'البحيرة',
  // 'Beni Suief': 'بني سويف',
  // 'Dakahlia': 'الدقهلية',
  // 'Damietta': 'دمياط',
  // 'Faiyuim': 'الفيوم',
  // 'Al-minya': 'المنيا',
  // 'Asyut': 'أسيوط',
  // 'Aswan': 'أسوان',
  // 'sidi beshr': 'سيدي بشر',
  // 'mamora': 'المعمورة',
  // 'el nozha': 'النزهه',
  // 'nasr city': 'مدينة نصر',
  // '6th octobr': '6 أكتوبر',
  // 'al obour': 'العبور',
  // 'maghagha': 'مغاغة',
  // 'samalout': 'سمالوط',
  // 'der mawas': 'ديرمواس',
  // 'aswan': 'أسوان',
  // 'adfo': 'إدفو',
  // 'kom ambo': 'كوم أمبو',
  // 'Badr': 'بدر',
  // 'Edku': 'إدكو',
  // 'rosetta': 'رشيد',
  // 'El Fashin': 'الفشن',
  // 'El Wasta': 'الوسطة',
  // 'Biba': 'ببا',
  // 'El Gamaliya': 'الجمالية',
  // 'El kurdi': 'الكردي',
  // 'Delqas': 'دلقاص',
  // 'El Zarqa': 'الزرقاء',
  // 'Faraskur': 'فارسكور',
  // 'Kafr Saad': 'كفر سعد',
  // 'Ibsgeway': 'إبسجوي',
  // 'Tamiya': 'طامية',
  // 'Itsa': 'إطسا',
  'Home': 'الصفحة الرئيسية',
  'Profile': 'الصفة الشخصية',
  'About Us': 'عن التطبيق',
  'Log Out': 'تسجيل الخروج',
  'Delete Post': 'حذف',
  'Edit Post': 'تعديل',
  'Report for this post': 'أبلغ عن هذا المنشور',
  'more details...': 'المزيد من التفاصيل...',
  'Report': 'Report',
  'age must be 18 and older': 'يجب أن يكون عمرك 18 عامًا أو أكبر',
  'phone number not 11 digits': 'لا يمكن أن يكون أقل من 11 رقم',
  'last name filed is require': 'الاسم الثاني مطلوب',
  'first name filed is require': 'الاسم الاول مطلوب',
  'first name': 'الاسم الاول',
  'last name': 'الاسم الثاني',
  'Update': 'تحديث',
  'age': 'العمر',
  'Enter contact email': 'أدخل البريد الإلكتروني',
  'contact email NOT sign in email': 'البريد الإلكتروني غير مسجل لدينا',
  'Age: ': 'العمر ',
  'Blood Type:': 'فصيلة الدم',
  'Contact Now': 'تواصل الان',
  'Start with sending new message': 'ابدأ بإرسال رسالة جديدة',
  'start chat with new message': 'ابدأ الدردشة برسالة جديدة',
  'Hi, I need': 'السلام عليكم أنا أحتاج إلي',
  'in ': 'في ',
  ' at ': ' في ',
  'before ': 'قبل ',
  'phone: 0': 'الهاتف: 0',
  'Chat': 'تواصل',
  'No Notification!': 'لا يوجد إشعارات!',
  'need a blood like your type': 'بحاجة إلى دم مثل فصيلة دمك',
  'Add Post': 'إضافة منشور',
  'blood type:    ': 'فصيلة الدم    ',
  'City:                ': 'مدينة       ',
  'Donation time:': 'وقت التبرع ',
  'Share': 'مشاركة',
  'phone:': ' الهاتف ',
  'age:': ' العمر ',
  "A website as well as a mobile application that provides a quick way for users who need a blood transfusion, for themselves or their families To find a donor when they need it. It also provides the opportunity for every donor who wishes to help to provide that assistance at a time when the patient needs it. This is done by registering in our system, and then the user shares a post with all the donors who are with him in this system, in which he requests the blood type he needs and the place and time he needs that type.The user can also search or communicate with other users through conversations. The system ensures that this is done as quickly as possible because delays in such a case could cost us a human life":
      "موقع إلكتروني بالإضافة إلى تطبيق للهاتف المحمول يوفر طريقة سريعة للمستخدمين الذين يحتاجون إلى نقل الدم ، لأنفسهم أو لعائلاتهم للعثور على متبرع عندما يحتاجون إليه. كما أنه يوفر الفرصة لكل متبرع يرغب في المساعدة في تقديم تلك المساعدة في الوقت الذي يحتاجها المريض يتم ذلك عن طريق التسجيل في نظامنا  ومن ثم يقوم المستخدم بمشاركة منشور مع جميع المتبرعين الموجودين معه في هذا النظام ، والذي يطلب فيه فصيلة الدم التي يحتاجها والمكان والزمان الذي يحتاج تلك الفصيلة يمكن للمستخدم أيضًا البحث أو التواصل مع مستخدمين آخرين من خلال المحادثات. يضمن النظام أن يتم ذلك في أسرع وقت ممكن لأن التأخير في مثل هذه الحالة قد يكلفنا حياة انسان",
  "Not Valid Account": "هذا الحساب غير موجود",
  "The email address is already in use by another account":
      "هذا الحساب موجود بالفعل",
};
