const Map<String, String> en = {
  'sign in': 'Sign In',
  'sign up': 'Sign Up',
  'localization': 'Localization',
  'Sign Up': 'Sign Up',
  'Sign in': 'Sign in',
  'Log In': 'Log In',
  'Enter your email': 'Enter your email',
  'Not valid email form': 'Not valid email form',
  'Type your message here...': 'Type your message here...',
  'Enter your password': 'Enter your password',
  'password must be at least 8 digits': 'password must be at least 8 digits',
  'email expression is not valid': 'email expression is not valid',
  'An error': 'An error',
  'email or password are wrong': 'email or password are wrong',
  'Okay': 'Okay',
  'Blood Bank': 'Blood Bank',
  'Developed By Hero Soft Company': 'Developed By Hero Soft Company',
  'Chats': 'Chats',
  'Search': 'Search',
  'No Chats!': 'No Chats!',
  'Post has been deleted': 'Post has been deleted',
  'no more details': 'no more details',
  'No posts shared!': 'No posts shared!',
  'filter users with blood type': 'filter users with blood type',
  'blood type:': 'blood type:',
  'Governorate: ': 'Governorate: ',
  'No users with this blood type': 'No users with this blood type',
  'click search to filter': 'click search to filter',
  'first name': 'first name',
  'can\'t be less than 3 digits': 'can\'t be less than 3 digits',
  'last name': 'last name',
  'Enter password': 'Enter password',
  'Confirm password': 'Confirm password',
  'Not the same as password': 'Not the same as password',
  'Enter Your Phone Number': 'Enter Your Phone Number',
  'can\'t be less than 11 number': 'can\'t be less than 11 number',
  'must be 18 or older': 'must be 18 or older',
  'blood type': 'blood type',
  'This email is already exist': 'This email is already exist',
  'Blood Bank  ': 'Blood Bank  ',
  // 'Alexandria': 'Alexandria',
  // 'Cairo': 'Cairo',
  // 'Beheira': 'Beheira',
  // 'Beni Suief': 'Beni Suief',
  // 'Dakahlia': 'Dakahlia',
  // 'Damietta': 'Damietta',
  // 'Faiyuim': 'Faiyuim',
  // 'Al-minya': 'Al-minya',
  // 'Asyut': 'Asyut',
  // 'Aswan': 'Aswan',
  // 'sidi beshr': 'Sidi Beshr',
  // 'mamora': 'Mamora',
  // 'el nozha': 'El Nozha',
  // 'nasr city': 'Nasr City',
  // '6th octobr': '6th Octobr',
  // 'al obour': 'Al Obour',
  // 'maghagha': 'Maghagha',
  // 'samalout': 'Samalout',
  // 'der mawas': 'Der Mawas',
  // 'aswan': 'Aswan',
  // 'adfo': 'Adfo',
  // 'kom ambo': 'Kom Ambo',
  // 'Badr': 'Badr',
  // 'Edku': 'Edku',
  // 'rosetta': 'rosetta',
  // 'El Fashin': 'El Fashin',
  // 'El Wasta': 'El Wasta',
  // 'Biba': 'Biba',
  // 'El Gamaliya': 'El Gamaliya',
  // 'El kurdi': 'El kurdi',
  // 'Delqas': 'Delqas',
  // 'El Zarqa': 'El Zarqa',
  // 'Faraskur': 'Faraskur',
  // 'Kafr Saad': 'Kafr Saad',
  // 'Ibsgeway': 'Ibsgeway',
  // 'Tamiya': 'Tamiya',
  // 'Itsa': 'Itsa',
  'Home': 'Home',
  'Profile': 'Profile',
  'About Us': 'About Us',
  'Log Out': 'Log Out',
  'Delete Post': 'Delete Post',
  'Edit Post': 'Edit Post',
  'Report for this post': 'Report for this post',
  'more details...': 'more details...',
  'Report': 'Report',
  'age must be 18 and older': 'age must be 18 and older',
  'phone number not 11 digits': 'Phone number not 11 digits',
  'last name filed is require': 'last name filed is require',
  'first name filed is require': 'first name filed is require',
  'Update': 'Update',
  'age': 'age',
  'Enter contact email': 'Enter contact email',
  'contact email NOT sign in email': 'contact email NOT sign in email',
  'Age: ': 'Age: ',
  'Blood Type:': 'Blood Type:',
  'Contact Now': 'Contact Now',
  'Start with sending new message': 'Start with sending new message',
  'start chat with new message': 'start chat with new message',
  'Hi, I need': 'Hi, I need',
  'in ': 'in ',
  ' at ': ' at ',
  'before ': 'before ',
  'phone: 0': 'phone: 0',
  'Chat': 'Chat',
  'No Notification!': 'No Notification!',
  'need a blood like your type': 'need a blood like your type',
  'Add Post': 'Add Post',
  'blood type:    ': 'blood type:    ',
  'City:                ': 'City:                ',
  'Donation time:': 'Donation time:',
  'Share': 'Share',
  'phone:': 'phone:',
  'age:': 'age:',
  "A website as well as a mobile application that provides a quick way for users who need a blood transfusion, for themselves or their families To find a donor when they need it. It also provides the opportunity for every donor who wishes to help to provide that assistance at a time when the patient needs it. This is done by registering in our system, and then the user shares a post with all the donors who are with him in this system, in which he requests the blood type he needs and the place and time he needs that type.The user can also search or communicate with other users through conversations. The system ensures that this is done as quickly as possible because delays in such a case could cost us a human life":
      "A website as well as a mobile application that provides a quick way for users who need a blood transfusion, for themselves or their families To find a donor when they need it. It also provides the opportunity for every donor who wishes to help to provide that assistance at a time when the patient needs it. This is done by registering in our system, and then the user shares a post with all the donors who are with him in this system, in which he requests the blood type he needs and the place and time he needs that type.The user can also search or communicate with other users through conversations. The system ensures that this is done as quickly as possible because delays in such a case could cost us a human life",
  "Not Valid Account": "Not Valid Account",
  "The email address is already in use by another account":
      "The email address is already in use by another account",
};
